# Generated by Django 3.2.16 on 2023-01-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
